# Generated by Django 4.0.6 on 2022-08-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherCurLocation', '0002_alter_location_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_daily_forecast',
            name='forecast_icon',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='user_daily_forecast',
            name='forecast_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
