# Generated by Django 4.0.6 on 2022-08-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherCurLocation', '0003_user_daily_forecast_forecast_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_daily_forecast',
            old_name='forecast_icon',
            new_name='day_icon',
        ),
        migrations.RemoveField(
            model_name='user_daily_forecast',
            name='precipitation_intensity',
        ),
        migrations.RemoveField(
            model_name='user_daily_forecast',
            name='precipitation_type',
        ),
        migrations.AddField(
            model_name='user_daily_forecast',
            name='day_precipitation_intensity',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user_daily_forecast',
            name='day_precipitation_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user_daily_forecast',
            name='night_icon',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user_daily_forecast',
            name='night_precipitation_intensity',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user_daily_forecast',
            name='night_precipitation_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
